Updated to test for network cam access before invoking getcams

diff --git a/run_cameras b/run_cameras
--- a/run_cameras
+++ b/run_cameras
@@ -1,5 +1,5 @@
 #!/bin/bash 
-version="v05302021"
+version="v06082021"
 # File: run_cameras
 
 # Variables now set in and accessed from external files config_runcam_vars and config_getcams_vars
@@ -169,10 +169,11 @@ finish() {
 	rm -f "$LOCK"
 	echo ": Trapped signal or exit, removed lockfile $LOCK and exiting"
 	logger -p notice -- "$(basename $0)[$$] was terminated: -- restart with  \"run_cameras -I\" if needed"
+	logger -p notice -- "$(basename $0)[$$] terminated: -- BASH_COMMAND is ${BASH_COMMAND}"
 	exit
 }
 
-trap 'finish $LINENO  $BASH_COMMAND' EXIT 1 2 3 6
+trap "finish $LINENO  ${BASH_COMMAND}" EXIT 1 2 3 6
 
 if [ -f "$LOCK" ] ;  #if script lockfile exists then 
 then
@@ -221,7 +222,7 @@ do
            camtype=${line[2]}
            # Terminate any running getcams whose camera has been disabled
            # Ensure valid camera entry first, rather than random comments
-           if [[ $camtype == "c" ]] || [[ camtype == "m" ]];
+           if [[ $camtype == "c" ]] || [[ $camtype == "m" ]];
            then
                if [[ -e "$lockpath/$quitcam_name-$camtype.lock" ]];
                then
@@ -241,10 +242,10 @@ do
 		then
 			continue    #Skip lines that are blank
 		fi
-		if [[ "$first_loop" = true ]] ;  
-        then
-            sleep $cam_delay # Start up cams 1 second apart 
-        fi
+		#if [[ "$first_loop" = true ]] ;  
+        #then
+            #sleep $cam_delay # Start up cams 1 second apart 
+        #fi
 		echo "Processing: ${line[*]}"
 		cam=${line[0]}
 		prog=${line[1]}
@@ -275,7 +276,7 @@ do
 			echo "In monitoring loop ... cam is $cam ... run_once is $run_once ... first_loop is $first_loop"
 			if [[ "$run_once" = "1" ]] ;
             then
-                sleep $cam_delay 
+                #sleep $cam_delay 
                 continue    # Run_once execution was already initiated the first time through loop, skip to next cam
             fi
 		fi
@@ -306,7 +307,13 @@ do
                 fi
             fi
         fi
-
+        ### Final check before getcams exec ... can we access the camera?
+        if ! error=$(ping -c 1 -W 1 $cam 2>&1 ); then
+            builtin echo "$(basename $0)[$$]: Ping failed: $cam not reachable ... error returned is $error" >> $log
+            logger -p notice -- "$(basename $0)[$pid] Ping failed: $cam not reachable ... error returned is $error"
+            sleep $cam_delay 
+            continue
+        fi
 		# If we got here, any leftover lock file has been removed and we now need to [re]start the camera fetch process 
         tstamp=$(date +"%Y%m%d.%H%M%S")
         #printf "$tstamp: $(basename $0)[$$]: Delay  before exec set to $delay\n" >> $log
@@ -316,6 +323,8 @@ do
         #printf "$tstamp: $(basename $0)[$$]: Delay  after exec set to $delay\n" >> $log
 		printf "$tstamp: $(basename $0)[$$]: Started [$lockpid] $epath/$prog $cam $camtype $delay $label $run_once $cpm $url\n" >> $log
 		echo "Wrote $lockpid to $lockpath/$cam-$camtype.lock" 
+        ### NOTE: ping/nslookup test above should preclude need for additional
+        ### delay between getcams invokations
 		#sleep $cam_delay  # Between subsequent cam_params line fetching 
 
 	done < $params
